# Exercise 1: Removing Duplicate Records

In [ ]:
import pandas as pd
df = pd.DataFrame({
    "student_id":[101, 102, 103, 102,104,101],
    "name":["Abel", "Sara", "Jhon", "Sara","Helen","Abel"],
    "score":[80,90,75,90,88,80]
})

Identify duplicate rows

In [ ]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

Count duplicated rows

In [ ]:
df.duplicated().sum()

np.int64(2)

Remove duplicates

In [ ]:
df.clean=df.drop_duplicates()
df.clean

/tmp/ipykernel_2694/2364330115.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.clean=df.drop_duplicates()

   student_id   name  score
0         101   Abel     80
1         102   Sara     90
2         103   Jhon     75
4         104  Helen     88

Keep only last occurance

In [ ]:
df_last= df.drop_duplicates(keep="last")
df_last

   student_id   name  score
2         103   Jhon     75
3         102   Sara     90
4         104  Helen     88
5         101   Abel     80

# Exercise 2: Duplicate Emails

In [ ]:
df= pd.DataFrame({
    "id":[1,2,3,4],
    "email":["a@gmail.com","b@gamil.com","a@gmail.com","c@gmail.com"]

})
df

   id        email
0   1  a@gmail.com
1   2  b@gamil.com
2   3  a@gmail.com
3   4  c@gmail.com

Find duplicated email

In [ ]:
df_duplicate_email=df[df.duplicated(subset="email")]
df_duplicate_email

   id        email
2   3  a@gmail.com

Remove duplicate email

In [ ]:
df_clean_dup_email=df.drop_duplicates(subset="email")
df_clean_dup_email

   id        email
0   1  a@gmail.com
1   2  b@gamil.com
3   4  c@gmail.com

# Exercise 3: Standardize City Names

In [ ]:
df=pd.DataFrame({
    "city":["addis ababa","ADDIS ABABA","Addis Ababa","adDis abAba"]
})

Convert to upper case

In [ ]:
df["upper"]=df["city"].str.upper()
df

          city        upper
0  addis ababa  ADDIS ABABA
1  ADDIS ABABA  ADDIS ABABA
2  Addis Ababa  ADDIS ABABA
3  adDis abAba  ADDIS ABABA

In [ ]:
df["lower"]=df["city"].str.lower()
df

          city        upper        lower
0  addis ababa  ADDIS ABABA  addis ababa
1  ADDIS ABABA  ADDIS ABABA  addis ababa
2  Addis Ababa  ADDIS ABABA  addis ababa
3  adDis abAba  ADDIS ABABA  addis ababa

In [ ]:
df["title"]=df["city"].str.title()
df

          city        upper        lower        title
0  addis ababa  ADDIS ABABA  addis ababa  Addis Ababa
1  ADDIS ABABA  ADDIS ABABA  addis ababa  Addis Ababa
2  Addis Ababa  ADDIS ABABA  addis ababa  Addis Ababa
3  adDis abAba  ADDIS ABABA  addis ababa  Addis Ababa

# Exercise 4: Remove Extra Spaces

In [ ]:
df = pd.DataFrame({
"name":[
" Abel",
"Sara ",
" John ",
" Helen"
]
})

Remove unnecessary spaces.

In [ ]:
df["name"]= df["name"].str.strip()
df

    name
0   Abel
1   Sara
2   John
3  Helen

# Exercise 5: Standardize Dates

In [ ]:
df = pd.DataFrame({
"date":[
"2026-01-05",
"05/02/2026",
"March 10, 2026",
"2026.04.15"
]
})

Convert to date

In [ ]:
df["date"] = pd.to_datetime(df["date"], format="mixed")
df

        date
0 2026-01-05
1 2026-05-02
2 2026-03-10
3 2026-04-15

 Standardize to YYYY-MM-DD

In [ ]:
df["date_standardized"] = df["date"].dt.strftime("%Y-%m-%d")
df

        date date_standardized
0 2026-01-05        2026-01-05
1 2026-05-02        2026-05-02
2 2026-03-10        2026-03-10
3 2026-04-15        2026-04-15

Extract year

In [ ]:

df["year"] = df["date"].dt.year
df

        date date_standardized  year
0 2026-01-05        2026-01-05  2026
1 2026-05-02        2026-05-02  2026
2 2026-03-10        2026-03-10  2026
3 2026-04-15        2026-04-15  2026

Extract month

In [ ]:
df["month"] = df["date"].dt.month
df

        date date_standardized  year  month
0 2026-01-05        2026-01-05  2026      1
1 2026-05-02        2026-05-02  2026      5
2 2026-03-10        2026-03-10  2026      3
3 2026-04-15        2026-04-15  2026      4

# Exercise 6: Kilograms to Pounds

In [ ]:
df = pd.DataFrame({
"weight_kg":[55,70,85,100]
})

Convert kilograms to pounds

In [ ]:
df["weight_lb"]=(df['weight_kg']*2.20462).round()
df["weight_lb"]

0    121.0
1    154.0
2    187.0
3    220.0
Name: weight_lb, dtype: float64

# Exercise 7: Celsius to Fahrenheit

In [ ]:
df = pd.DataFrame({
"temp_c":[0,25,37,100]
})

Convert Celsius to Fahrenheit.

In [ ]:
df["temp_f"]= (df["temp_c"]* 9/5) + 32
df

   temp_c  temp_f
0       0    32.0
1      25    77.0
2      37    98.6
3     100   212.0

# Exercise 8: Handling Missing Values

In [ ]:

df = pd.DataFrame({
"name":["Abel","Sara",None,"John"],
"age":[20,np.nan,25,30]
})
df

   name   age
0  Abel  20.0
1  Sara   NaN
2  None  25.0
3  John  30.0

Find missing values

In [ ]:
df_missing =df.isnull()
df_missing

    name    age
0  False  False
1  False   True
2   True  False
3  False  False

Fill missing ages with mean

In [ ]:
df["age"]=df["age"].fillna(df["age"].mean())
df

   name   age
0  Abel  20.0
1  Sara  25.0
2  None  25.0
3  John  30.0

Fill missing names with Unknown

In [ ]:
df["name"] = df["name"].fillna("Unknown")
df

      name   age
0     Abel  20.0
1     Sara  25.0
2  Unknown  25.0
3     John  30.0

# Exercise 9: Correct Data Entry Errors

In [ ]:
df = pd.DataFrame({
"gender":[
"Male",
"male",
"MALE",
"Female",
"female"
]
})

Standardize gender values

In [ ]:
df["gender"]=df["gender"].str.title()
df

   gender
0    Male
1    Male
2    Male
3  Female
4  Female

# Exercise 10: Currency Conversion

In [ ]:
df = pd.DataFrame({
"salary_usd":[500,800,1200,1500]
})

In [ ]:
exchange_rate=150
df["salary_usd"]=df["salary_usd"]*exchange_rate
df

   salary_usd
0       75000
1      120000
2      180000
3      225000

# Exercise 11: Outlier Detection

In [ ]:
df = pd.DataFrame({
"salary":[3500,4000,4200,3900,4100,45000]
})

### Calculate Q1 and Q3

In [ ]:
Q1= df["salary"].quantile(0.25)
Q3=df["salary"].quantile(0.75)
print(Q1,"\n")
print(Q3)

3925.0

4175.0

Calculate IQR

In [ ]:
IQR= Q3 - Q1
print(IQR)

250.0

Identify outliers

In [ ]:
lower = Q1 - 1.5 * IQR
upper= Q3 + 1.5 * IQR
outliners = df[(df["salary"] < lower) | (df["salary"] > upper)]
outliners

   salary
0    3500
5   45000

Remove outliers

In [ ]:
Clean_outliners_df= df[(df["salary"]>= lower) & (df["salary"]<= upper)]
Clean_outliners_df

   salary
1    4000
2    4200
3    3900
4    4100

# Exercise 12: Phone Number
# Standardization

In [ ]:
df = pd.DataFrame({
"phone":[
"0911223344",
"+251911223344",
"251911223344",
"0911-223-344"
]
})

Remove symbols

In [ ]:
df["phone"]= df["phone"].str.replace("-","", regex=False)
df["phone"]=df["phone"].str.replace("+","",regex=False)
df

          phone
0    0911223344
1  251911223344
2  251911223344
3    0911223344

Convert all numbers to +251 format

In [ ]:
df["phone"]=df["phone"].apply(
    lambda x: "+251" + x[1:] if x.startswith("0") else "+251" + x[3:]
)
df

            phone
0  +2511911223344
1  +2511911223344
2  +2511911223344
3  +2511911223344

# Exercise 13: Email Cleaning

In [ ]:
df = pd.DataFrame({
"email":[
" ABEL@GMAIL.COM ",
"sara@gmail.com",
"JOHN@YAHOO.COM"
]
})

Remove spaces

In [ ]:
df["email"] = df["email"].str.strip()
df

            email
0  ABEL@GMAIL.COM
1  sara@gmail.com
2  JOHN@YAHOO.COM

Convert to lowercase

In [ ]:
df["email"] = df["email"].str.lower()
df

            email
0  abel@gmail.com
1  sara@gmail.com
2  john@yahoo.com

Validate emails

In [ ]:
df["valid"] = df["email"].str.contains("@")
df

            email  valid
0  abel@gmail.com   True
1  sara@gmail.com   True
2  john@yahoo.com   True

# Exercise 14: Product Name Normalization

In [ ]:
#Dataframe
df = pd.DataFrame({
"product":[
"Laptop",
"laptop",
"LAPTOP",
"Laptop "
]
})

Standardize product names and Compare unique counts before and after cleaning

In [ ]:
print("Before:", df["product"].nunique())
df['product']=df['product'].str.strip().str.lower()
print("After:", df["product"].nunique(),"\n")
print(df)

Before: 1
After: 1

  product
0  laptop
1  laptop
2  laptop
3  laptop

# Exercise 15: Mixed Data Cleaning
# Challenge

In [ ]:
#Dataset
import numpy as np
import pandas as pd

df = pd.DataFrame({
"name":[" Abel ","Sara",None,"JOHN"],
"age":[20,np.nan,25,30],
"salary":[4000,4500,5000,45000],
"join_date":[
"2026-01-01",
"01/02/2026",
"March 10, 2026",
"2026.04.15"
]
})

Clean names.

In [ ]:
df["name"]=df["name"].fillna("Unknown").str.strip().str.lower().str.title()
df

      name   age  salary       join_date
0     Abel  20.0    4000      2026-01-01
1     Sara  25.0    4500      01/02/2026
2  Unknown  25.0    5000  March 10, 2026
3     John  30.0   45000      2026.04.15

Fill missing values

In [ ]:
df["age"]=df["age"].fillna(df["age"].mean())
df

      name   age  salary       join_date
0     Abel  20.0    4000      2026-01-01
1     Sara  25.0    4500      01/02/2026
2  Unknown  25.0    5000  March 10, 2026
3     John  30.0   45000      2026.04.15

Standardize dates

In [ ]:
df["join_date"] = pd.to_datetime(df["join_date"],format="mixed")
df

     name   age  salary  join_date
0   Abel   20.0    4000 2026-01-01
1    Sara   NaN    4500 2026-01-02
2    None  25.0    5000 2026-03-10
3    JOHN  30.0   45000 2026-04-15

Detect outliers

In [ ]:
Q1 = df["salary"].quantile(0.25)
Q3 = df["salary"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
outliers = df[
(df["salary"] < lower) |
(df["salary"] > upper)
]

print(df)

print("Outliers")

print(outliers)

      name   age  salary       join_date
0     Abel  20.0    4000      2026-01-01
1     Sara  25.0    4500      01/02/2026
2  Unknown  25.0    5000  March 10, 2026
3     John  30.0   45000      2026.04.15
Outliers
   name   age  salary   join_date
3  John  30.0   45000  2026.04.15