In [1]:
import pandas as pd

In [60]:
csv=pd.read_csv("testss.csv")

In [61]:
df=pd.DataFrame(csv)

In [62]:
print (df)

       #   Country,Other  TotalCases  NewCases  TotalDeaths  NewDeaths  \
0      1             USA   111820082       NaN    1219487.0        NaN
1      2           India    45035393       NaN     533570.0        NaN
2      3          France    40138560       NaN     167642.0        NaN
3      4         Germany    38828995       NaN     183027.0        NaN
4      5          Brazil    38743918       NaN     711380.0        NaN
..   ...             ...         ...       ...          ...        ...
226  227         Tokelau          80       NaN          NaN        NaN
227  228    Vatican City          29       NaN          NaN        NaN
228  229  Western Sahara          10       NaN          1.0        NaN
229  230      MS Zaandam           9       NaN          2.0        NaN
230  231           China      503302       NaN       5272.0        NaN

     TotalRecovered  NewRecovered  ActiveCases  Serious,Critical  ...  \
0       109814428.0           NaN     786167.0             940.0  ...
1               NaN           NaN          NaN               NaN  ...
2        39970918.0           NaN          0.0               NaN  ...
3        38240600.0           NaN     405368.0               NaN  ...
4        36249161.0           NaN    1783377.0               NaN  ...
..              ...           ...          ...               ...  ...
226             NaN           NaN         80.0               NaN  ...
227            29.0           NaN          0.0               NaN  ...
228             9.0           NaN          0.0               NaN  ...
229             7.0           NaN          0.0               NaN  ...
230        379053.0           NaN     118977.0               NaN  ...

       TotalTests  Tests/1M pop    Population          Continent  \
0    1.186852e+09     3544901.0  3.348053e+08      North America
1    9.358795e+08      665334.0  1.406632e+09               Asia
2    2.714902e+08     4139547.0  6.558452e+07             Europe
3    1.223324e+08     1458359.0  8.388360e+07             Europe
4    6.377617e+07      296146.0  2.153536e+08      South America
..            ...           ...           ...                ...
226           NaN           NaN  1.378000e+03  Australia/Oceania
227           NaN           NaN  7.990000e+02             Europe
228           NaN           NaN  6.261610e+05             Africa
229           NaN           NaN           NaN                NaN
230  1.600000e+08      110461.0  1.448471e+09               Asia

     1 Caseevery X ppl 1 Deathevery X ppl  1 Testevery X ppl  \
0                  3.0              275.0                0.0
1                 31.0             2636.0                2.0
2                  2.0              391.0                0.0
3                  2.0              458.0                1.0
4                  6.0              303.0                3.0
..                 ...                ...                ...
226               17.0                NaN                NaN
227               28.0                NaN                NaN
228            62616.0           626161.0                NaN
229                NaN                NaN                NaN
230             2878.0           274748.0                9.0

     New Cases/1M pop  New Deaths/1M pop  Active Cases/1M pop
0                 NaN                NaN               2348.0
1                 NaN                NaN                  0.4
2                 NaN                NaN                  NaN
3                 NaN                NaN               4833.0
4                 NaN                NaN               8281.0
..                ...                ...                  ...
226               NaN                NaN              58055.0
227               NaN                NaN                  NaN
228               NaN                NaN                  NaN
229               NaN                NaN                  NaN
230               NaN                NaN                 82.0

[231 rows x 22 columns]

In [52]:
df[df['Country,Other'] == 'Ethiopia']

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,TotalTests,Tests/1M pop,Population,Continent,1 Caseevery X ppl,1 Deathevery X ppl,1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
91,92,Ethiopia,501157,NaN,7574.0,NaN,488171.0,NaN,5412.0,NaN,...,5565340.0,46066.0,120812698.0,Africa,241.0,15951.0,22.0,NaN,NaN,45.0

In [54]:
#Total death in ethiopia
df.loc[df['Country,Other'] == 'Ethiopia', ['Country,Other', 'TotalDeaths']]

   Country,Other  TotalDeaths
91      Ethiopia       7574.0

In [68]:
#Top 10 countries with highest total death
df[['Country,Other', 'TotalDeaths']].sort_values('TotalDeaths',ascending=False).head(10)

   Country,Other  TotalDeaths
0            USA    1219487.0
4         Brazil     711380.0
1          India     533570.0
9         Russia     402756.0
17        Mexico     334958.0
8             UK     232112.0
34          Peru     222161.0
7          Italy     196487.0
3        Germany     183027.0
2         France     167642.0

In [69]:
df[['Country,Other', 'TotalRecovered']].sort_values('TotalRecovered',ascending=False).head(10)

   Country,Other  TotalRecovered
0            USA     109814428.0
2         France      39970918.0
3        Germany      38240600.0
4         Brazil      36249161.0
5       S. Korea      34535939.0
7          Italy      26361218.0
8             UK      24678275.0
9         Russia      23545818.0
11         Spain      13762417.0
12     Australia      11820014.0

In [96]:
#using iloc
test=(df['TotalDeaths'] > 1000).sum()
print(test)
test_iloc=df['TotalDeaths'] 
print(test_iloc.iloc[1])

133
533570.0

In [82]:
df.isnull()

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,TotalTests,Tests/1M pop,Population,Continent,1 Caseevery X ppl,1 Deathevery X ppl,1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
0,False,False,False,True,False,True,False,True,False,False,...,False,False,False,False,False,False,False,True,True,False
1,False,False,False,True,False,True,True,True,True,True,...,False,False,False,False,False,False,False,True,True,False
2,False,False,False,True,False,True,False,True,False,True,...,False,False,False,False,False,False,False,True,True,True
3,False,False,False,True,False,True,False,True,False,True,...,False,False,False,False,False,False,False,True,True,False
4,False,False,False,True,False,True,False,True,False,True,...,False,False,False,False,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,False,False,False,True,True,True,True,True,False,True,...,True,True,False,False,False,True,True,True,True,False
227,False,False,False,True,True,True,False,True,False,True,...,True,True,False,False,False,True,True,True,True,True
228,False,False,False,True,False,True,False,True,False,True,...,True,True,False,False,False,False,True,True,True,True
229,False,False,False,True,False,True,False,True,False,True,...,True,True,True,True,True,True,True,True,True,True
230,False,False,False,True,False,True,False,True,False,True,...,False,False,False,False,False,False,False,True,True,False

In [103]:
df[df['Country,Other'].str.contains('a')]

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,TotalTests,Tests/1M pop,Population,Continent,1 Caseevery X ppl,1 Deathevery X ppl,1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
1,2,India,45035393,NaN,533570.0,NaN,NaN,NaN,NaN,NaN,...,935879495.0,665334.0,1.406632e+09,Asia,31.0,2636.0,2.0,NaN,NaN,0.4
2,3,France,40138560,NaN,167642.0,NaN,39970918.0,NaN,0.0,NaN,...,271490188.0,4139547.0,6.558452e+07,Europe,2.0,391.0,0.0,NaN,NaN,NaN
3,4,Germany,38828995,NaN,183027.0,NaN,38240600.0,NaN,405368.0,NaN,...,122332384.0,1458359.0,8.388360e+07,Europe,2.0,458.0,1.0,NaN,NaN,4833.0
4,5,Brazil,38743918,NaN,711380.0,NaN,36249161.0,NaN,1783377.0,NaN,...,63776166.0,296146.0,2.153536e+08,South America,6.0,303.0,3.0,NaN,NaN,8281.0
5,6,S. Korea,34571873,NaN,35934.0,NaN,34535939.0,NaN,0.0,NaN,...,15804065.0,307892.0,5.132990e+07,Asia,1.0,1428.0,3.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,227,Tokelau,80,NaN,NaN,NaN,NaN,NaN,80.0,NaN,...,NaN,NaN,1.378000e+03,Australia/Oceania,17.0,NaN,NaN,NaN,NaN,58055.0
227,228,Vatican City,29,NaN,NaN,NaN,29.0,NaN,0.0,NaN,...,NaN,NaN,7.990000e+02,Europe,28.0,NaN,NaN,NaN,NaN,NaN
228,229,Western Sahara,10,NaN,1.0,NaN,9.0,NaN,0.0,NaN,...,NaN,NaN,6.261610e+05,Africa,62616.0,626161.0,NaN,NaN,NaN,NaN
229,230,MS Zaandam,9,NaN,2.0,NaN,7.0,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230,231,China,503302,NaN,5272.0,NaN,379053.0,NaN,118977.0,NaN,...,160000000.0,110461.0,1.448471e+09,Asia,2878.0,274748.0,9.0,NaN,NaN,82.0