In [3]:
import pandas as pd
import numpy as np
students = pd.DataFrame({
"student_id":[101,102,103,104,105,106,107,108,109,110],
"name":
["Abel","Sara",None,"John","Marta",None,"David","Helen","Tom",None],
"department":["CS","IT","CS",None,"SE","IT","SE",None,"CS","IT"],
"gpa":[3.5,3.8,np.nan,2.9,3.7,np.nan,3.2,3.4,3.9,np.nan],
"scholarship":
[5000,np.nan,3000,2000,np.nan,4000,3500,np.nan,5000,np.nan]
})
students

In [11]:
#Missing value
students.isnull()

   student_id   name  department    gpa  scholarship
0       False  False       False  False        False
1       False  False       False  False         True
2       False   True       False   True        False
3       False  False        True  False        False
4       False  False       False  False         True
5       False   True       False   True        False
6       False  False       False  False        False
7       False  False        True  False         True
8       False  False       False  False        False
9       False   True       False   True         True

In [12]:
#count missing value
students.isnull().sum()

student_id     0
name           3
department     2
gpa            3
scholarship    4
dtype: int64

In [13]:
#Total number of missing value
students.isnull().sum().sum()

np.int64(12)

In [14]:
#Percentage of missing value - help to determine whether a column should be cleaned, imputed, or removed.
(students.isnull().sum())/len(students)*100

student_id      0.0
name           30.0
department     20.0
gpa            30.0
scholarship    40.0
dtype: float64

In [27]:
#display all columns
students.columns

Index(['student_id', 'name', 'department', 'gpa', 'scholarship'], dtype='str')

In [18]:
#Display only column that contain misssing value
students.columns[students.isnull().any()]

Index(['name', 'department', 'gpa', 'scholarship'], dtype='str')

In [31]:
#Display all rows that contain at least one missing value
students[students.isnull().any(axis=1)]

   student_id   name department  gpa  scholarship
1         102   Sara         IT  3.8          NaN
2         103    NaN         CS  NaN       3000.0
3         104   John        NaN  2.9       2000.0
4         105  Marta         SE  3.7          NaN
5         106    NaN         IT  NaN       4000.0
7         108  Helen        NaN  3.4          NaN
9         110    NaN         IT  NaN          NaN

In [35]:
#Display students whose GPA is missing.
students[students["gpa"].isnull()]

   student_id name department  gpa  scholarship
2         103  NaN         CS  NaN       3000.0
5         106  NaN         IT  NaN       4000.0
9         110  NaN         IT  NaN          NaN

In [37]:
#Display students whose scholarship information is missing.
students[students["scholarship"].isnull()]

   student_id   name department  gpa  scholarship
1         102   Sara         IT  3.8          NaN
4         105  Marta         SE  3.7          NaN
7         108  Helen        NaN  3.4          NaN
9         110    NaN         IT  NaN          NaN

In [40]:
#Exercise 9
#Replace missing names with "Unknown".
students["name"]=students["name"].fillna("Unknown")
students["name"]

0       Abel
1       Sara
2    Unknown
3       John
4      Marta
5    Unknown
6      David
7      Helen
8        Tom
9    Unknown
Name: name, dtype: str

In [45]:
#Exercise 10
#Replace missing GPA values using the mean GPA.
students["gpa"]=students["gpa"].fillna(students["gpa"].mean())
students["gpa"]

0    3.500000
1    3.800000
2    3.485714
3    2.900000
4    3.700000
5    3.485714
6    3.200000
7    3.400000
8    3.900000
9    3.485714
Name: gpa, dtype: float64

In [48]:
#Exercise 11
#Replace missing GPA values using the median GPA.
students["gpa"]=students["gpa"].fillna(students["gpa"].median())
students["gpa"]

0    3.500000
1    3.800000
2    3.485714
3    2.900000
4    3.700000
5    3.485714
6    3.200000
7    3.400000
8    3.900000
9    3.485714
Name: gpa, dtype: float64

In [50]:
#Exercise 12
#Replace missing department values using the most common department.
students["department"]=students["department"].fillna(students["department"].mode()[0])
students["department"]

0    CS
1    IT
2    CS
3    CS
4    SE
5    IT
6    SE
7    CS
8    CS
9    IT
Name: department, dtype: str

In [51]:
#Exercise 13
#Replace missing scholrship values with zero
students["scholarship"] = students["scholarship"].fillna(0)
students["scholarship"]

0    5000.0
1       0.0
2    3000.0
3    2000.0
4       0.0
5    4000.0
6    3500.0
7       0.0
8    5000.0
9       0.0
Name: scholarship, dtype: float64

In [52]:
#Exercise 14
#remove missing rows
students.dropna()

   student_id     name department       gpa  scholarship
0         101     Abel         CS  3.500000       5000.0
1         102     Sara         IT  3.800000          0.0
2         103  Unknown         CS  3.485714       3000.0
3         104     John         CS  2.900000       2000.0
4         105    Marta         SE  3.700000          0.0
5         106  Unknown         IT  3.485714       4000.0
6         107    David         SE  3.200000       3500.0
7         108    Helen         CS  3.400000          0.0
8         109      Tom         CS  3.900000       5000.0
9         110  Unknown         IT  3.485714          0.0

In [53]:
#Exercise 15
#Remove missing columns
students.dropna(axis=1)

   student_id     name department       gpa  scholarship
0         101     Abel         CS  3.500000       5000.0
1         102     Sara         IT  3.800000          0.0
2         103  Unknown         CS  3.485714       3000.0
3         104     John         CS  2.900000       2000.0
4         105    Marta         SE  3.700000          0.0
5         106  Unknown         IT  3.485714       4000.0
6         107    David         SE  3.200000       3500.0
7         108    Helen         CS  3.400000          0.0
8         109      Tom         CS  3.900000       5000.0
9         110  Unknown         IT  3.485714          0.0

In [56]:
#Exercise 16
#Create a GPA missing-value flag.
students["gpa_missing"] = students["gpa"].isnull()
students["gpa_missing"]

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: gpa_missing, dtype: bool

In [57]:
#Exercise 17
#Create a scholarship missing-value flag.
students["scholarship_missing"] = students["scholarship"].isnull()
students["scholarship_missing"]

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: scholarship_missing, dtype: bool

In [58]:
#Exercise 18
#Find the column with the highest number of missing values.
students.isnull().sum().idxmax()

'student_id'

In [59]:
#Exercise 19
#Find the column with the lowest number of missing values.
students.isnull().sum().idxmin()

'student_id'

In [60]:
#Exercise 20
#Calculate dataset completeness percentage.
100-(students.isnull().sum().sum()/ students.size)*100

np.float64(100.0)

In [ ]:
#Part II: Iterating Over Rows and Columns

In [61]:
#Exercise 21
#Print all column names.
for col in students.columns:
    print(col)

student_id
name
department
gpa
scholarship
gpa_missing
scholarship_missing

In [62]:
#Exercise 22
#Print each column name and its data type.
for col in students.columns:
    print(col, students[col].dtype)

student_id int64
name str
department str
gpa float64
scholarship float64
gpa_missing bool
scholarship_missing bool

In [63]:
#Exercise 23
#Print all student names using iterrows()
for index, row in students.iterrows():
    print(row["name"])

Abel
Sara
Unknown
John
Marta
Unknown
David
Helen
Tom
Unknown

In [64]:
#Exercise 24
#Print student names and GPA.
for index, row in students.iterrows():
    print(row["name"], row["gpa"])

Abel 3.5
Sara 3.8
Unknown 3.4857142857142853
John 2.9
Marta 3.7
Unknown 3.4857142857142853
David 3.2
Helen 3.4
Tom 3.9
Unknown 3.4857142857142853

In [65]:
#Exercise 25
#Print students whose GPA is above 3.5.
for index, row in students.iterrows():
    if row["gpa"] > 3.5:
        print(row["name"])

Sara
Marta
Tom

In [66]:
#Exercise 26
#Print all scholarship recipients.
for index, row in students.iterrows():
    if row["scholarship"] > 0:
        print(row["name"])

Abel
Unknown
John
Unknown
David
Tom

In [70]:
#Exercise 27
#Create GPA categories using iteration.
categories = []

for index, row in students.iterrows():
    if row["gpa"] >= 3.7:
        categories.append("Excellent")
    elif row["gpa"] >= 3.0:
        categories.append("Good")
    else:
        categories.append("At Risk")

students["category"] = categories

students["category"]

0         Good
1    Excellent
2         Good
3      At Risk
4    Excellent
5         Good
6         Good
7         Good
8    Excellent
9         Good
Name: category, dtype: str

In [71]:
#Exercise 28
#Print all rows using itertuples() .
for row in students.itertuples():

    print(
    row.student_id,
    row.name
    )

101 Abel
102 Sara
103 Unknown
104 John
105 Marta
106 Unknown
107 David
108 Helen
109 Tom
110 Unknown

In [72]:
#Exercise 29
#Count students by department using iteration only.
counts = {}

for index, row in students.iterrows():

    dept = row["department"]
    
    counts[dept] = counts.get(dept, 0) + 1

print(counts)

{'CS': 5, 'IT': 3, 'SE': 2}

In [73]:
#Exercise 30
#Generate a student summary report.
for index, row in students.iterrows():

    print(f"Student ID: {row['student_id']}")
    print(f"Name: {row['name']}")
    print(f"Department: {row['department']}")
    print(f"GPA: {row['gpa']}")
    print("-" * 30)

Student ID: 101
Name: Abel
Department: CS
GPA: 3.5
------------------------------
Student ID: 102
Name: Sara
Department: IT
GPA: 3.8
------------------------------
Student ID: 103
Name: Unknown
Department: CS
GPA: 3.4857142857142853
------------------------------
Student ID: 104
Name: John
Department: CS
GPA: 2.9
------------------------------
Student ID: 105
Name: Marta
Department: SE
GPA: 3.7
------------------------------
Student ID: 106
Name: Unknown
Department: IT
GPA: 3.4857142857142853
------------------------------
Student ID: 107
Name: David
Department: SE
GPA: 3.2
------------------------------
Student ID: 108
Name: Helen
Department: CS
GPA: 3.4
------------------------------
Student ID: 109
Name: Tom
Department: CS
GPA: 3.9
------------------------------
Student ID: 110
Name: Unknown
Department: IT
GPA: 3.4857142857142853
------------------------------